---
layout: cv
title: Nephi Zaugg's CV
---
# Nephi Zaugg
Computer Scientist, BYU-Idaho Student.

<div id="webaddress">
<a href="https://github.com/MushuMan/ZARepo">Github Repo</a>
</div>


## Currently

Studying Computer Science at Brigham Young University Idaho. 

### Specialized in

Backend development, problem solving, learning, python, and c#.


### Research interests

Backend development, computer systems, foundational development.


## Education

`2020`
__Tillamook High School/ORVED__

`2023 - now`
__Brigham Young University Idaho__

- Computer Science Major


## Occupation

`2018`
__Cafe Associate__, Tillamook Creamery (503 815 1300)
- Took customer orders and provided assistance.

`2019-2021 | 2025-Present`
__Machine Operator/Packager__, Stowaway Gourmet (385 242 4651)
- Worked to package food and maintain a clean and dry environment.
- Professional Dish Washer.

`2022`
__Unarmed Security Guard__, The Church of Jesus Christ of Latter-Day Saints (801 722 5001)
- Oversaw film set during the night.

`2023`
__Retail Warehouse Associate__, Tillamook Creamery (503 815 1300)
- Priced items for the Creamery Visitor's Center.

`2024`
__IT Assistant__, Tillamook Family Counseling Center
- Maintained IT infrastructure and helped with projects.



<!-- ### Footer

Last updated: July 2026 -->